import { createRequire } from 'node:module'
import assert from 'node:assert/strict'
const require = createRequire(process.env.CODEX_NODE_MODULES + '/package.json')
const { chromium } = require('playwright')
const browser = await chromium.launch({ channel: 'msedge', headless: true })
const context = await browser.newContext({ viewport: { width: 393, height: 852 }, deviceScaleFactor: 3, isMobile: true, hasTouch: true })
const page = await context.newPage()
const errors = []
page.on('pageerror', error => errors.push(error.message))
const idiom = { pinyin: 'huà lóng diǎn jīng', explanation: '比喻在关键处点明要旨。', origin: '历代名画记', example: '这句话画龙点睛。', usage: '作谓语', relatedIdioms: ['锦上添花', '恰到好处', '点石成金'] }
const compare = { meaningDiff: '画龙点睛：突出重点\n锦上添花：增加美好', usageDiff: '画龙点睛：关键处\n锦上添花：已有成果', scenarios: '画龙点睛：文章\n锦上添花：成果', confusionPoints: '画龙点睛：必要\n锦上添花：额外' }
let delay = 0, status = 200
const requests = []
await page.route('https://api.deepseek.com/**', async route => {
  if (route.request().url().endsWith('/user/balance')) return route.fulfill({ json: { is_available: true, balance_infos: [{ currency: 'CNY', total_balance: '18.50', granted_balance: '0.00', topped_up_balance: '18.50' }] } })
  if (route.request().method() === 'GET') return route.fulfill({ json: { data: [{ id: 'deepseek-flash' }, { id: 'test-model' }] } })
  const body = route.request().postDataJSON(); requests.push(body)
  await new Promise(r => setTimeout(r, delay))
  if (status !== 200) return route.fulfill({ status, json: { error: { message: 'Model unavailable' } } })
  return route.fulfill({ json: { choices: [{ message: { content: body.messages[0].content.includes('对比') ? JSON.stringify(compare) : body.messages[1].content === 'Reply OK.' ? 'OK' : JSON.stringify(idiom) } }], usage: { total_tokens: 80 } } })
})
await page.goto('http://127.0.0.1:5173/wordLearning/#/profile')
assert.equal(await page.getByText('个人设置', { exact: true }).count(), 0)
assert.equal(await page.getByLabel('API Key', { exact: true }).count(), 0)
await page.getByRole('button', { name: '模型与 API', exact: true }).click()
await page.getByLabel('API Key', { exact: true }).fill('test-key-only')
await page.getByRole('button', { name: '获取模型', exact: true }).click()
await page.getByLabel('可用模型').selectOption('test-model')
await page.getByRole('button', { name: '测试连接', exact: true }).click()
await page.getByRole('status').filter({ hasText: '连接成功' }).waitFor()
await page.getByRole('button', { name: '保存并启用' }).click()
await page.reload()
await page.getByText('当前模型：test-model', { exact: true }).waitFor()
await page.locator('nav').getByRole('button', { name: '学习', exact: true }).click()
await page.getByPlaceholder('输入成语或词语…').fill('画龙点睛')
const search = page.getByRole('button', { name: '搜索', exact: true })
const before = await search.boundingBox()
delay = 1800
await search.click()
const during = await page.getByRole('button', { name: '生成中', exact: true }).boundingBox()
assert.equal(before.width, during.width)
await page.locator('nav').getByRole('button', { name: '对比', exact: true }).click()
await page.getByPlaceholder('输入词语 1').fill('画龙点睛')
await page.getByPlaceholder('输入词语 2').fill('锦上添花')
await page.getByRole('button', { name: '开始对比', exact: true }).click()
await page.locator('nav').getByRole('button', { name: '个人', exact: true }).click()
await page.getByText('¥18.50', { exact: true }).waitFor()
await page.waitForTimeout(2100)
await page.locator('nav').getByRole('button', { name: '学习', exact: true }).click()
await page.getByText(idiom.explanation, { exact: true }).waitFor()
await page.getByText('消耗 80 tokens', { exact: true }).waitFor()
assert.equal(await page.locator('text=相关成语').locator('..').locator('..').locator('button').count(), 3)
assert.equal(await page.getByPlaceholder('输入成语或词语…').inputValue(), '画龙点睛')
await page.locator('nav').getByRole('button', { name: '对比', exact: true }).click()
assert.equal(await page.getByPlaceholder('输入词语 1').inputValue(), '画龙点睛')
await page.getByText('含义区别', { exact: true }).waitFor()
await page.locator('nav').getByRole('button', { name: '记录', exact: true }).click()
const row = page.locator('[role=button]').filter({ hasText: '画龙点睛' }).first()
const source = await row.boundingBox()
await row.click()
await page.getByRole('dialog').waitFor()
await page.waitForTimeout(120)
const middle = await page.locator('.record-panel').boundingBox()
assert(middle.height > source.height && middle.height < 840)
await page.waitForTimeout(620)
await page.screenshot({ path: 'tests/record-expanded.png' })
await page.getByRole('button', { name: '返回记录' }).click()
await page.getByRole('dialog').waitFor({ state: 'detached' })
assert(Math.abs((await row.boundingBox()).y - source.y) < 1)
await page.getByRole('button', { name: /对比记录/ }).click()
await page.locator('[role=button]').filter({ hasText: '画龙点睛' }).first().click()
await page.getByRole('dialog').getByText('含义区别', { exact: true }).waitFor()
await page.keyboard.press('Escape')
await page.getByRole('dialog').waitFor({ state: 'detached' })
await page.emulateMedia({ reducedMotion: 'reduce' })
await page.locator('[role=button]').filter({ hasText: '画龙点睛' }).first().click()
await page.getByRole('button', { name: '返回记录' }).click()
await page.getByRole('dialog').waitFor({ state: 'detached' })
await page.locator('nav').getByRole('button', { name: '学习', exact: true }).click()
status = 404; delay = 0
await page.getByPlaceholder('输入成语或词语…').fill('一心一意')
await page.getByRole('button', { name: '搜索', exact: true }).click()
await page.getByText(/HTTP 404：接口路径或模型不存在/).waitFor()
assert(requests.every(r => r.model === 'test-model'))
await page.locator('nav').getByRole('button', { name: '个人', exact: true }).click()
await page.getByRole('button', { name: '模型与 API', exact: true }).click()
await page.getByRole('button', { name: '新增配置' }).click()
await page.getByLabel('配置名称', { exact: true }).fill('备用配置')
await page.getByLabel('API URL', { exact: true }).fill('https://api.deepseek.com/v1/chat/completions')
await page.getByLabel('API Key', { exact: true }).fill('second-test-key')
await page.getByRole('button', { name: '获取模型', exact: true }).click()
await page.getByLabel('可用模型').waitFor()
await page.getByRole('button', { name: '保存并启用' }).click()
const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('settings-store')))
assert.equal(saved.profiles.length, 2)
await page.getByLabel('切换已保存配置').selectOption(saved.profiles[0].id)
await page.getByText('当前模型：test-model', { exact: true }).waitFor()
status = 401
await page.getByRole('button', { name: '测试连接', exact: true }).click()
await page.getByRole('status').filter({ hasText: 'HTTP 401' }).waitFor()
const endpoints = await page.evaluate(async () => {
  const { apiEndpoint } = await import('/wordLearning/src/api/deepseek.ts')
  return [apiEndpoint('https://api.example.com/v1/', 'models'), apiEndpoint('https://api.example.com/v1/chat/completions', 'chat/completions')]
})
assert.deepEqual(endpoints, ['https://api.example.com/v1/models', 'https://api.example.com/v1/chat/completions'])
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
assert.deepEqual(errors, [])
console.log(JSON.stringify({ passed: true, requests: requests.length, viewport: '393x852', buttonWidth: before.width, animationMidHeight: middle.height, errors }))
await browser.close()
