import { createRequire } from 'node:module'
import assert from 'node:assert/strict'
const require = createRequire(process.env.CODEX_NODE_MODULES + '/package.json')
const { chromium } = require('playwright')
const browser = await chromium.launch({ channel: 'msedge', headless: true })
const page = await browser.newPage({ viewport: { width: 393, height: 852 }, isMobile: true, hasTouch: true })
const errors = []
page.on('pageerror', error => errors.push(error.message))
const issues = [
  { id:'a', createdAt:Date.now(), tokenUsage:80, articles:[{ title:'关于推动高质量发展和现代化建设的重要论述', shortTitle:'高质量发展新实践', source:'导入 PDF', url:'', publishedAt:'', content:'因地制宜推进高质量发展。'.repeat(120), words:['因地制宜','高质量发展'], analysis:'', origin:'pdf', page:1 }], pdf:{ fingerprint:'a'.repeat(64), filename:'rmrb.pdf', pages:1, remainder:'', model:'mimo', usageEstimated:false, articleIndex:0, articleCount:2 } },
  { id:'b', createdAt:Date.now()-1000, tokenUsage:70, articles:[{ title:'完整长标题第二篇文章用于阅读页面展示', shortTitle:'基层治理协同创新', source:'导入 PDF', url:'', publishedAt:'', content:'久久为功提升基层治理效能。'.repeat(50), words:['久久为功'], analysis:'', origin:'pdf', page:1, completedAt:Date.now(), starred:true }], pdf:{ fingerprint:'a'.repeat(64), filename:'rmrb.pdf', pages:1, remainder:'', model:'mimo', usageEstimated:false, articleIndex:1, articleCount:2 } }
]
await page.addInitScript(value => localStorage.setItem('daily-store', JSON.stringify({issues:value,selectedId:'a'})), issues)
await page.goto(process.env.DAILY_TEST_URL || 'http://127.0.0.1:5173/wordLearning/#/report')
await page.getByRole('heading',{name:/关于推动高质量发展/}).waitFor()
const app = page.locator('#app')
const indicatorBefore = await page.locator('#bottom-nav-indicator').boundingBox()
await app.evaluate(el => el.scrollTo({top:600}))
const indicatorWidths = []
for (let i=0;i<7;i++) { await page.waitForTimeout(80); indicatorWidths.push((await page.locator('#bottom-nav-indicator').boundingBox()).width) }
const compact = await page.locator('.nav-frame').boundingBox()
assert(compact.width <= 73)
assert(Math.max(...indicatorWidths) <= indicatorBefore.width + 1)
assert(indicatorWidths.at(-1) < indicatorBefore.width)
assert.equal(await page.getByRole('button',{name:'返回日报顶部'}).count(),1)
await page.getByRole('button',{name:'返回日报顶部'}).click()
await page.waitForFunction(() => document.querySelector('#app').scrollTop < 5)
await page.waitForTimeout(550)
const expanded = await page.locator('.nav-frame').boundingBox()
assert(expanded.width > 350)
await page.getByRole('button',{name:'添加星标'}).click()
assert.equal(await page.getByRole('button',{name:'取消星标'}).count(),1)
const starStyle = await page.getByRole('button',{name:'取消星标'}).evaluate(el => { const s=getComputedStyle(el); return {background:s.backgroundColor,color:s.color} })
assert.equal(starStyle.background,'rgba(0, 0, 0, 0)')
assert.equal(starStyle.color,'rgb(255, 199, 44)')
const trigger = page.getByRole('button',{name:'查看历史日报'}), triggerBox = await trigger.boundingBox()
await trigger.click(); await page.waitForTimeout(120)
const panel = page.getByRole('dialog',{name:'历史日报'}), mid = await panel.boundingBox()
assert(mid.width > triggerBox.width && mid.width < 480)
await page.waitForTimeout(450)
await panel.getByText('高质量发展新实践',{exact:true}).waitFor()
const titleStyle = await panel.getByText('高质量发展新实践',{exact:true}).evaluate(el => getComputedStyle(el).fontWeight)
assert(Number(titleStyle) >= 600)
const firstBody = panel.locator('.history-row-body').first(), firstBox = await firstBody.boundingBox(), stateBox = await firstBody.getByText('未学完',{exact:true}).boundingBox()
assert(firstBox.width >= 280)
assert(stateBox.x > firstBox.x + firstBox.width * .65)
assert.equal(await panel.getByLabel('已星标').count(),2)
const row = panel.locator('.history-row-body').first(), box = await row.boundingBox()
await row.dispatchEvent('pointerdown',{pointerId:1,clientX:box.x+250,clientY:box.y+30})
await row.dispatchEvent('pointermove',{pointerId:1,clientX:box.x+150,clientY:box.y+32})
await row.dispatchEvent('pointerup',{pointerId:1,clientX:box.x+150,clientY:box.y+32})
await page.waitForTimeout(350)
assert.notEqual(await row.evaluate(el => getComputedStyle(el).transform),'none')
const remove = panel.getByRole('button',{name:'删除高质量发展新实践'}); await remove.waitFor(); await remove.click()
assert.equal(await panel.getByText('高质量发展新实践',{exact:true}).count(),0)
await panel.getByRole('button',{name:'关闭历史日报'}).click(); await panel.waitFor({state:'detached'})
await page.getByRole('button',{name:'生成日报',exact:true}).click(); await page.getByRole('button',{name:/PDF 日报导入/}).click()
const pdf = page.getByRole('dialog',{name:'PDF 日报导入'}); await pdf.waitFor(); await pdf.getByRole('button',{name:'选择 PDF 文件'}).waitFor()
const chooser = page.waitForEvent('filechooser'); await pdf.getByRole('button',{name:'选择 PDF 文件'}).click(); (await chooser).setFiles('E:/QuarkDownload/03_学习数据与阅读资料/rmrb2026091401.pdf')
await pdf.getByText('原文已提取，尚未调用模型',{exact:true}).waitFor({timeout:30000})
await pdf.getByRole('button',{name:'重新选择 PDF'}).waitFor()
assert.equal(await pdf.getByText(/核对原始提取文字/).count(),0)
await pdf.getByRole('button',{name:'关闭'}).click(); await pdf.waitFor({state:'detached'})
assert.equal(await page.getByText(/以下为所上传版面的文字/).count(),0)
assert.equal(await page.getByText('学习进度',{exact:true}).count(),0)
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true)
assert.deepEqual(errors,[])
console.log(JSON.stringify({passed:true,viewport:'393x852',compactWidth:compact.width,expandedWidth:expanded.width,historyMidWidth:mid.width,starred:true,swipeDelete:true,pdfButton:true,errors}))
await browser.close()
