import assert from 'node:assert/strict'
import { launchBrowser, base } from './helpers/browser.mjs'
const browser = await launchBrowser()
const page = await browser.newPage({ viewport: { width: 393, height: 852 }, isMobile: true, hasTouch: true })
const errors = []
async function motionScreenshot(path) {
  await page.evaluate(() => {
    window.__pausedMotion = document.getAnimations().filter(a => a.playState === 'running')
    window.__pausedMotion.forEach(a => a.pause())
  })
  await page.screenshot({ path })
  await page.evaluate(() => window.__pausedMotion.forEach(a => a.play()))
}
page.on('pageerror', e => errors.push(e.message))
await page.addInitScript(() => localStorage.setItem('settings-store', JSON.stringify({ apiKey: 'test-only', model: 'deepseek-flash', baseUrl: 'https://api.deepseek.com' })))
await page.route('https://api.deepseek.com/**', async route => {
  await new Promise(r => setTimeout(r, 1300))
  const comparison = route.request().postDataJSON().messages[0].content.includes('对比')
  const data = comparison ? { meaningDiff:'词义不同', usageDiff:'用法不同', scenarios:'文章语境', confusionPoints:'注意语境' } : { pinyin:'huà lóng diǎn jīng', explanation:'比喻在关键处点明要旨。', origin:'历代名画记', example:'这句话画龙点睛。', usage:'作谓语', relatedIdioms:['锦上添花','恰到好处','点石成金'] }
  await route.fulfill({ json: { choices:[{message:{content:JSON.stringify(data)}}] } })
})
const nav = async name => { await page.locator('nav').getByRole('button', { name, exact:true }).click(); await page.waitForTimeout(450) }
await page.goto(`${base}#/learn`)
assert.equal(await page.getByText('最近学习', { exact:true }).count(),0)
const circle = await page.locator('.generation-surface').boundingBox()
assert.equal(circle.width,80)
await page.getByPlaceholder('输入成语或词语…').fill('画龙点睛')
await page.getByRole('button',{name:'搜索',exact:true}).click()
await page.waitForTimeout(140)
const middle = await page.locator('.generation-surface').boundingBox()
assert(middle.width > 80 && middle.width < 361)
assert.equal(await page.locator('.is-expanding').count(),1)
await motionScreenshot('docs/.local/browser-artifacts/first-search-middle.png')
await page.getByText('比喻在关键处点明要旨。', {exact:true}).waitFor()
await page.getByPlaceholder('输入成语或词语…').fill('锦上添花')
await page.getByRole('button',{name:'搜索',exact:true}).click()
assert.equal(await page.locator('.is-expanding').count(),0)
await page.getByRole('status', {name:'正在生成内容'}).waitFor()
await page.getByText('比喻在关键处点明要旨。', {exact:true}).waitFor()
await nav('对比')
const add = await page.getByRole('button',{name:'添加词语'}).boundingBox()
const compare = await page.getByRole('button',{name:'开始对比'}).boundingBox()
assert(Math.abs(add.y - compare.y)<2)
assert(compare.x>add.x)
await page.screenshot({path:'docs/.local/browser-artifacts/compare-compact.png'})
await page.getByPlaceholder('输入词语 1').fill('画龙点睛')
await page.getByPlaceholder('输入词语 2').fill('锦上添花')
await page.getByRole('button',{name:'开始对比'}).click()
await page.waitForTimeout(140)
assert.equal(await page.locator('.is-expanding').count(),1)
await page.getByText('词义不同', {exact:true}).waitFor()
await nav('记录')
const row = page.locator('[role=button]').filter({hasText:'画龙点睛'}).first()
await row.click()
await page.waitForTimeout(160)
assert.equal(await page.locator('.record-shared-title').count(),1)
const font = await page.locator('.record-shared-title').evaluate(el=>parseFloat(getComputedStyle(el).fontSize))
assert(font>16 && font<48)
const outgoingTime = await page.locator('.record-row-ghost [data-row-time]').evaluate(el => ({ opacity: +getComputedStyle(el).opacity, y: new DOMMatrix(getComputedStyle(el).transform).m42 }))
assert(outgoingTime.opacity < 1 && outgoingTime.y > 0)
assert(await page.locator('.record-row-ghost [data-row-icon]').evaluate(el => +getComputedStyle(el).opacity) < 1)
await motionScreenshot('docs/.local/browser-artifacts/title-expand-middle.png')
await page.waitForTimeout(600)
assert.equal(await page.locator('.record-shared-title').count(),0)
assert.equal(await page.locator('.record-back').evaluate(el=>getComputedStyle(el).borderBottomWidth),'0px')
await page.locator('.record-back').focus()
assert.equal(await page.locator('.record-back').evaluate(el=>getComputedStyle(el).outlineStyle),'none')
assert.equal(await page.locator('.record-row-ghost > svg').evaluate(el => +getComputedStyle(el).opacity), 0)
await page.screenshot({path:'docs/.local/browser-artifacts/glass-light.png'})
await page.evaluate(() => document.documentElement.classList.add('dark'))
await page.waitForTimeout(400)
await page.screenshot({path:'docs/.local/browser-artifacts/glass-dark.png'})
await page.evaluate(() => document.documentElement.classList.remove('dark'))
await page.getByRole('button',{name:'返回记录'}).click()
await page.waitForTimeout(180)
assert.equal(await page.locator('.record-shared-title').count(),1)
const incomingTime = await page.locator('.record-row-ghost [data-row-time]').evaluate(el => new DOMMatrix(getComputedStyle(el).transform).m42)
assert(incomingTime > 0)
await motionScreenshot('docs/.local/browser-artifacts/title-return-middle.png')
await page.getByRole('dialog').waitFor({state:'detached'})
await row.click()
await page.getByRole('button',{name:'返回记录'}).click()
await page.getByRole('dialog').waitFor({state:'detached'})
await page.getByRole('button',{name:/对比记录/}).click()
await page.locator('[role=button]').filter({hasText:'画龙点睛'}).first().click()
await page.waitForTimeout(100)
assert.equal(await page.locator('.record-shared-title').count(),2)
await page.waitForTimeout(700)
await page.getByRole('button',{name:'返回记录'}).click()
await page.getByRole('dialog').waitFor({state:'detached'})
await nav('个人')
await page.screenshot({path:'docs/.local/browser-artifacts/profile-compact.png'})
assert.equal(await page.locator('.model-settings').count(),0)
assert.equal(await page.getByText('个人设置',{exact:true}).count(),0)
await page.getByRole('button',{name:'模型与 API',exact:true}).click()
await page.getByLabel('API Key',{exact:true}).waitFor()
await page.getByRole('button',{name:'返回个人'}).click()
await page.locator('.model-settings').waitFor({state:'detached'})
assert.equal(await page.locator('.model-settings').count(),0)
await page.emulateMedia({ reducedMotion:'reduce' })
await nav('记录')
await page.locator('[role=button]').filter({hasText:'画龙点睛'}).first().click()
await page.getByRole('button',{name:'返回记录'}).click()
await page.getByRole('dialog').waitFor({state:'detached'})
assert.deepEqual(errors,[])
console.log(JSON.stringify({passed:true, circleWidth:circle.width, expandingWidth:middle.width, sharedTitleFont:font, errors}))
await browser.close()
