import assert from 'node:assert/strict'
import { launchBrowser, base } from './helpers/browser.mjs'
const browser = await launchBrowser()
try {
  const page = await browser.newPage({ viewport: { width: 393, height: 852 }, reducedMotion: 'reduce' })
  const errors = [], requests = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route('https://provider.example.test/**', async route => {
    requests.push({ url: route.request().url(), authorization: route.request().headers().authorization })
    await route.fulfill({ json: { data: [{ id: 'model-a' }, { id: 'model-b' }] } })
  })
  await page.goto(`${base}#/profile/models`)
  await page.getByRole('button', { name: '添加模型服务商', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '模型服务商配置' })
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await dialog.getByText('请填写 API Key', { exact: true }).waitFor()
  await dialog.getByLabel('名称', { exact: true }).fill('Mock Provider')
  await dialog.getByLabel('API 地址', { exact: true }).fill('https://provider.example.test/v1')
  await dialog.getByLabel('API Key', { exact: true }).fill('test-only-key')
  await dialog.getByRole('button', { name: '获取列表', exact: true }).click()
  await dialog.getByText('已获取 2 个模型', { exact: true }).waitFor()
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await dialog.waitFor({ state: 'detached' })
  assert.equal(requests.length, 1)
  assert.equal(requests[0].url, 'https://provider.example.test/v1/models')
  assert.equal(requests[0].authorization, 'Bearer test-only-key')
  await page.locator('#learning-model-select').selectOption({ label: 'Mock Provider · model-a' })
  await page.locator('#pdf-model-select').selectOption({ label: 'Mock Provider · model-b' })
  await page.reload()
  assert.equal(await page.locator('#learning-model-select option:checked').textContent(), 'Mock Provider · model-a')
  assert.equal(await page.locator('#pdf-model-select option:checked').textContent(), 'Mock Provider · model-b')
  await page.getByRole('button', { name: '编辑模型服务商', exact: true }).click()
  await dialog.getByLabel('名称', { exact: true }).fill('Renamed Provider')
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await dialog.waitFor({ state: 'detached' })
  await page.getByText('Renamed Provider', { exact: true }).waitFor()
  assert.deepEqual(errors, [])
  console.log(JSON.stringify({ passed: true, checks: 'validation, mocked discovery, save/edit, independent learning/PDF selection, reload persistence', requests: requests.length }))
} finally { await browser.close() }
