import { mkdir } from 'node:fs/promises'
import assert from 'node:assert/strict'
import { launchBrowser, base } from './helpers/browser.mjs'
await mkdir('docs/.local', { recursive: true })
const browser = await launchBrowser()
const page=await browser.newPage({viewport:{width:393,height:852}});const errors=[];page.on('pageerror',e=>errors.push(e.message))
await page.route('https://**/*',r=>r.fulfill({json:{}}))
await page.goto(`${base}#/profile`)
await page.getByText('登录后同步',{exact:true}).waitFor()
await page.evaluate(async()=>{
 const {cloudbaseRdb}=await import('/wordLearning/src/services/cloudbase.ts')
 window.testRemote=null
 cloudbaseRdb.from=()=>({select(){return this},eq(){return this},gt(){return this},async limit(){return {data:window.testRemote?[window.testRemote]:[],error:null}},async upsert(record){window.testRemote=structuredClone(record);return {data:null,error:null}}})
 const {useAuthStore}=await import('/wordLearning/src/stores/auth.ts')
 const {useSettingsStore}=await import('/wordLearning/src/stores/settings.ts')
 useSettingsStore().saveProfile({id:'test',name:'MiMo',apiKey:'test-only-ui-secret',baseUrl:'https://api.xiaomimimo.com/v1',model:'',models:['mimo-pdf','mimo-tts']})
 localStorage.setItem('word-learning-cloud-sync:test-ui-user',JSON.stringify({choice:'merge-local-to-cloud',completedAt:1}))
 const auth=useAuthStore();auth.currentUser={id:'test-ui-user',displayName:'测试用户'};auth.initialized=true
})
for (const width of [320,375,390,430]) {
 await page.setViewportSize({width,height:852})
 const main=page.locator('.profile-sync-main');await main.waitFor()
 const data=main.locator('.profile-sync-data');const button=main.getByRole('button',{name:'立即同步',exact:true})
 const [mainBox,localBox,buttonBox,cloudBox]=await Promise.all([main.boundingBox(),data.nth(0).boundingBox(),button.boundingBox(),data.nth(1).boundingBox()])
 assert(mainBox&&localBox&&buttonBox&&cloudBox)
 assert(localBox.x+localBox.width<=buttonBox.x+1&&buttonBox.x+buttonBox.width<=cloudBox.x+1)
 assert(Math.abs((localBox.y+localBox.height/2)-(buttonBox.y+buttonBox.height/2))<2)
 assert(Math.abs((cloudBox.y+cloudBox.height/2)-(buttonBox.y+buttonBox.height/2))<2)
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),true)
}
await page.setViewportSize({width:393,height:852})
await page.getByRole('button',{name:'未开启',exact:true}).waitFor()
await page.getByRole('button',{name:'未开启',exact:true}).click()
await page.getByLabel('同步口令',{exact:true}).fill('test-ui-long-passphrase')
await page.getByLabel('确认口令',{exact:true}).fill('test-ui-long-passphrase')
await page.getByRole('button',{name:'开启加密同步',exact:true}).click()
await page.getByRole('button',{name:'已解锁',exact:true}).waitFor()
await page.waitForFunction(()=>window.testRemote?.payload?.apiSettings?.ciphertext)
const wire=await page.evaluate(()=>JSON.stringify(window.testRemote));assert(!wire.includes('test-only-ui-secret'))
assert(!wire.includes('test-ui-long-passphrase'))
await page.getByText(/最近结果：成功/).waitFor()
assert.equal(await page.getByText(/上次成功/).count()>0,true)
await page.getByRole('button',{name:/备份与清理/}).click()
const downloadPromise=page.waitForEvent('download')
await page.getByRole('button',{name:'创建备份',exact:true}).click()
await downloadPromise
await page.getByRole('button',{name:'恢复',exact:true}).waitFor()
const localBackup=await page.evaluate(()=>localStorage.getItem('word-learning-local-backups-v1')||'')
assert(localBackup.includes('word-learning-backup'))
assert(!localBackup.includes('test-only-ui-secret'))
assert(!localBackup.includes('test-ui-long-passphrase'))
await page.getByRole('button',{name:'恢复',exact:true}).click()
const summaryDialog=page.getByRole('dialog',{name:'备份恢复摘要'})
await summaryDialog.waitFor()
await summaryDialog.getByText(/0 词 · 0 复习/).waitFor()
await summaryDialog.getByRole('button',{name:'继续恢复',exact:true}).click()
const confirmDialog=page.getByRole('dialog',{name:'再次确认恢复'})
await confirmDialog.waitFor()
await confirmDialog.getByRole('button',{name:'确认恢复',exact:true}).click()
await page.getByText('备份恢复成功',{exact:true}).waitFor()

await page.screenshot({path:'docs/.local/sync-mobile.png',fullPage:true})
await page.getByRole('button',{name:'已解锁',exact:true}).click()
await page.getByRole('button',{name:'忘记此设备的解锁密钥',exact:true}).click()
await page.getByRole('button',{name:'待解锁',exact:true}).waitFor()
await page.getByLabel('同步口令',{exact:true}).fill('wrong-test-passphrase')
await page.getByRole('button',{name:'解锁并恢复',exact:true}).click()
await page.getByRole('alert').filter({hasText:'同步口令不正确'}).waitFor()
for(const width of [320,1280]){
 await page.setViewportSize({width,height:900})
 await page.goto(`${base}#/profile/models`)
 await page.getByRole('button',{name:'添加模型服务商',exact:true}).click()
 await page.waitForTimeout(780)
 const rect=await page.locator('.provider-editor-dialog').boundingBox();assert(rect.x>=0&&rect.x+rect.width<=width+1)
 await page.locator('.provider-editor-dialog').getByRole('button',{name:'保存',exact:true}).click()
 await page.getByText('请填写 API Key',{exact:true}).waitFor()
 await page.keyboard.press('Escape');await page.waitForTimeout(560)
}
assert.deepEqual(errors,[])
console.log(JSON.stringify({passed:['cloud sync data and action stay compact at 320/375/390/430px','no horizontal overflow','last sync time/result/type','cloud sync UI enables encrypted upload','wire excludes API key and passphrase','safe local backup excludes credentials','backup summary and two-step restore confirmation','forget device key','wrong-passphrase UI','320px and desktop dialog fit','empty API key validation'],errors}))
await browser.close()
